baseURL = "https://www.zedongpeng.com/"

languageCode = "en-us"
title = "Zedong Peng"
theme = "papermod"

[params]
  mainSections = []   # 不列出任何 section
  disableThemeToggle = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "CV"
url = "/pdf/cv.pdf"
weight = 4


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
